# Generated by Django 4.2.11 on 2024-07-09 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(default=1)),
                ("shot_id", models.IntegerField(default=1)),
                ("measurement_date", models.DateTimeField(auto_now_add=True)),
                ("gravity_center", models.JSONField()),
                ("quaternion", models.JSONField()),
                ("sliders_value", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measurement_date"],
            },
        ),
    ]
